import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {createServer} from '../../tools/serve.mjs';
let tmp,server,browser,origin;
before(async()=>{
 tmp=fs.mkdtempSync(path.join(os.tmpdir(),'eva-floating-policy-'));
 for(const name of ['prototype','vendor'])fs.symlinkSync(path.resolve('dist',name),path.join(tmp,name),'dir');
 const css=fs.readFileSync('dist/index.html','utf8').match(/<link[^>]+stylesheet[^>]*>/g).join('\n');
 const code=`import React from 'react';import{createRoot}from'react-dom/client';import{Popover,FloatingForm}from'./prototype/063-popover.jsx';import{Popconfirm}from'./prototype/063-popconfirm.jsx';import{Form}from'./prototype/063-forms.jsx';
 class Boundary extends React.Component{constructor(p){super(p);this.state={error:null};}static getDerivedStateFromError(error){return {error};}render(){return this.state.error?<p role="alert">{this.state.error.message}</p>:this.props.children;}}
 function App(){const[bad,setBad]=React.useState(false);const[custom,setCustom]=React.useState(false),[show,setShow]=React.useState(true),[calls,setCalls]=React.useState(0),[done,setDone]=React.useState(false);const next=React.useRef(),finish=React.useRef();return <>
 <button ref={next}>后续入口</button><button onClick={()=>setBad(true)}>错误组合</button>{bad&&<Boundary><FloatingForm.Fields><Form.Input field="illegal"/></FloatingForm.Fields></Boundary>}
 <section aria-label="独立组合"><FloatingForm onCancel={()=>{}} onSubmit={()=>setDone(true)}><Form.Input type="hidden" field="hidden" fieldStyle={{display:"none"}}/><FloatingForm.Fields><Form.Input field="wrapped" label="嵌套字段" extraText="字段帮助"/><Form.Input field="nestedNext" label="下一项"/></FloatingForm.Fields><Form.Input field="outside" label="组外字段" extraText="末项帮助" rules={[{required:true,message:"请填写组外字段"}]}/></FloatingForm></section>
 <Popover trigger="click" title="填写信息" content={<><button>帮助</button><input disabled aria-label="禁用"/><input hidden aria-label="隐藏"/><div style={{display:'none'}}><input aria-label="折叠"/></div><input aria-label="可填写"/></>}><button>打开表单</button></Popover>
 <Popover trigger="custom" visible={custom} returnFocus={()=>next.current} onEscKeyDown={()=>setCustom(false)} title="受控浮层" content={<button onClick={()=>setCustom(false)}>关闭受控</button>}><button onClick={()=>setCustom(true)}>打开受控</button></Popover>
 {show&&<Popover trigger="click" title="移除入口" returnFocus={()=>next.current} content={<button onClick={()=>setShow(false)}>完成并移除入口</button>}><button>待移除入口</button></Popover>}
 <Popover trigger="click" aria-label="无标题浮层" content="无标题正文"><button>无标题</button></Popover>
 <Popover trigger="click" title="简单说明" description content="可供朗读的简短说明"><button>说明</button></Popover>
 <Popover trigger="click" title="结构化内容" content={<><p>第一段</p><p>第二段</p></>}><button>多段</button></Popover>
 <Popover trigger="click" title="大内容" content={<div>{Array.from({length:50},(_,i)=><p key={i}>很长的内容与不能截断的详细说明 {i}</p>)}<button>末尾动作</button></div>}><button>长内容</button></Popover>
 <Popover trigger="click" motion={false} title="多字段表单" content={<FloatingForm id="matrix-form" onCancel={()=>{}}><Form.Input field="name" label="名称"/><Form.Input field="note" label="备注" extraText="帮助说明"/></FloatingForm>}><button>多字段布局</button></Popover>
 <Popover trigger="click" title="无权限" content={<FloatingForm id="disabled-form" disabled onCancel={()=>{}}><span>无编辑权限</span></FloatingForm>}><button>禁用提交</button></Popover>
 <Popconfirm title="失败重试" content="确认后执行" description onConfirm={()=>{setCalls(c=>c+1);if(calls===0)throw Error('保存失败，请重试');setDone(true);}}><button>确认事务</button></Popconfirm><output aria-label="调用次数">{calls}</output>{done&&<p>事务完成</p>}
 <Popconfirm title="异步确认" onConfirm={()=>new Promise((resolve,reject)=>{finish.current={resolve,reject};})}><button>异步事务</button></Popconfirm><button onClick={()=>finish.current?.resolve()}>完成旧请求</button><button onClick={()=>finish.current?.reject(Error('旧请求失败'))}>结束旧请求</button>
 </>};createRoot(document.getElementById('app')).render(<App/>);`;
 const result=await build({stdin:{contents:code,loader:'jsx',resolveDir:process.cwd()},bundle:true,write:false,loader:{'.css':'empty'}});
 fs.writeFileSync(path.join(tmp,'app.js'),result.outputFiles[0].text);fs.writeFileSync(path.join(tmp,'index.html'),`${css}<div id="app" style="padding:70px 16px"></div><script src="app.js"></script>`);
 server=createServer(tmp);await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({channel:'msedge'});
});
after(async()=>{await browser?.close();await new Promise(r=>server?.close(r));fs.rmSync(tmp,{recursive:true,force:true});});
async function scenario(fn,viewport={width:1200,height:800}){const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(3000);try{await page.goto(origin);await fn(page);assert.deepEqual(errors,[]);}finally{await page.close();}}
test('初始焦点跳过隐藏和禁用字段',()=>scenario(async p=>{await p.getByRole('button',{name:'打开表单',exact:true}).click();await p.getByRole('dialog',{name:'填写信息'}).waitFor();assert.equal(await p.getByRole('textbox',{name:'可填写'}).evaluate(e=>e===document.activeElement),true);}));
test('受控关闭和入口卸载后回到指定后续入口',()=>scenario(async p=>{await p.getByRole('button',{name:'打开受控',exact:true}).click();await p.getByRole('button',{name:'关闭受控'}).click();await p.getByRole('dialog',{name:'受控浮层'}).waitFor({state:'hidden'});assert.equal(await p.getByRole('button',{name:'后续入口'}).evaluate(e=>e===document.activeElement),true);await p.getByRole('button',{name:'待移除入口'}).click();await p.getByRole('button',{name:'完成并移除入口'}).click();assert.equal(await p.getByRole('button',{name:'后续入口'}).evaluate(e=>e===document.activeElement),true);}));
test('简单说明按需关联，复杂内容不整段播报',()=>scenario(async p=>{await p.getByRole('button',{name:'说明',exact:true}).click();const d=p.getByRole('dialog',{name:'简单说明'});assert.equal(await d.evaluate(e=>document.getElementById(e.getAttribute('aria-describedby'))?.textContent),'可供朗读的简短说明');await p.keyboard.press('Escape');await p.getByRole('button',{name:'多段',exact:true}).click();assert.equal(await p.getByRole('dialog',{name:'结构化内容'}).getAttribute('aria-describedby'),null);}));
test('失败保留确认框、播报错误并可重试',()=>scenario(async p=>{await p.getByRole('button',{name:'确认事务',exact:true}).click();const d=p.getByRole('dialog',{name:'失败重试'});await d.getByRole('button',{name:'确定',exact:true}).click();await d.getByRole('alert').waitFor();assert.equal(await d.getByRole('alert').innerText(),'保存失败，请重试');await d.getByRole('button',{name:'确定',exact:true}).click();await d.waitFor({state:'hidden'});await p.getByText('事务完成',{exact:true}).waitFor();assert.equal(await p.getByLabel('调用次数').innerText(),'2');}));
test('关闭重开不接收旧确认请求的错误',()=>scenario(async p=>{await p.getByRole('button',{name:'异步事务',exact:true}).click();const d=p.getByRole('dialog',{name:'异步确认'});await d.getByRole('button',{name:'确定',exact:true}).click();await d.getByRole('button',{name:'取消',exact:true}).click();await d.waitFor({state:'hidden'});await p.getByRole('button',{name:'结束旧请求'}).click();await p.getByRole('button',{name:'异步事务',exact:true}).click();await d.waitFor();assert.equal(await d.getByRole('alert').count(),0);assert.equal(await d.getByRole('button',{name:'确定',exact:true}).isEnabled(),true);}));
test('按钮支持业务禁用',()=>scenario(async p=>{await p.getByRole('button',{name:'禁用提交'}).click();assert.equal(await p.getByRole('dialog',{name:'无权限'}).getByRole('button',{name:'保存'}).isEnabled(),false);}));
test('小窗口内容可滚动且不超出视口',()=>scenario(async p=>{await p.getByRole('button',{name:'长内容',exact:true}).click();const d=p.getByRole('dialog',{name:'大内容'});await d.waitFor();const box=await d.boundingBox();assert.ok(box.width<=280&&box.height<=320,JSON.stringify(box));await d.getByRole('button',{name:'末尾动作'}).scrollIntoViewIfNeeded();assert.equal(await d.getByRole('button',{name:'末尾动作'}).isVisible(),true);},{width:280,height:320}));

test('无标题浮层使用显式可访问名称',()=>scenario(async p=>{await p.getByRole('button',{name:'无标题',exact:true}).click();await p.getByRole('dialog',{name:'无标题浮层',exact:true}).waitFor();}));
test('旧请求成功不关闭重新打开的确认框',()=>scenario(async p=>{await p.getByRole('button',{name:'异步事务',exact:true}).click();const d=p.getByRole('dialog',{name:'异步确认'});await d.getByRole('button',{name:'确定',exact:true}).click();await d.getByRole('button',{name:'取消',exact:true}).click();await d.waitFor({state:'hidden'});await p.getByRole('button',{name:'异步事务',exact:true}).click();await d.waitFor();await p.getByRole('button',{name:'完成旧请求'}).evaluate(e=>e.click());await p.evaluate(()=>new Promise(requestAnimationFrame));assert.equal(await d.isVisible(),true);assert.equal(await d.getByRole('alert').count(),0);}));
test('点击外部入口不抢回焦点',()=>scenario(async p=>{await p.getByRole('button',{name:'打开表单',exact:true}).click();await p.getByRole('button',{name:'后续入口'}).click();await p.getByRole('dialog',{name:'填写信息'}).waitFor({state:'hidden'});assert.equal(await p.getByRole('button',{name:'后续入口'}).evaluate(e=>e===document.activeElement),true);}));

test('Popover 表单统一默认控件规格和多字段间距',()=>scenario(async p=>{await p.getByRole('button',{name:'多字段布局'}).click();const d=p.getByRole('dialog',{name:'多字段表单'});const actual=await d.evaluate(e=>{const fields=e.querySelectorAll('.semi-form-field'),labels=e.querySelectorAll('.semi-form-field-label'),input=fields[0].querySelector('.semi-input-wrapper'),button=Array.from(e.querySelectorAll('button')).find(n=>n.textContent==='保存');return {interField:labels[1].getBoundingClientRect().top-input.getBoundingClientRect().bottom,labelGap:input.getBoundingClientRect().top-labels[0].getBoundingClientRect().bottom,weights:Array.from(labels,n=>getComputedStyle(n).fontWeight),buttonHeight:button.getBoundingClientRect().height,buttonFont:getComputedStyle(button).fontSize};});assert.deepEqual(actual,{interField:20,labelGap:8,weights:['400','400'],buttonHeight:32,buttonFont:'14px'});}));

test('表单组合不依赖 Popover 祖先，隐藏及嵌套字段不重复留白且自动关联提交按钮',()=>scenario(async p=>{const section=p.getByRole('region',{name:'独立组合'});const actual=await section.evaluate(e=>{const form=e.querySelector('form'),label=e.querySelector('label[for="wrapped"]')?.closest('.semi-form-field-label')||e.querySelectorAll('.semi-form-field-label')[1],field=e.querySelector('[field="wrapped"]')||e.querySelectorAll('.semi-form-field')[1],button=Array.from(e.querySelectorAll('button')).find(n=>n.textContent==='保存');return {labelWeight:getComputedStyle(label).fontWeight,top:label.getBoundingClientRect().top-form.getBoundingClientRect().top,bottom:getComputedStyle(field).paddingBottom,linked:!!form.id&&button.getAttribute('form')===form.id};});assert.deepEqual(actual,{labelWeight:'400',top:0,bottom:'0px',linked:true});const geometry=()=>section.evaluate(e=>{const fields=Array.from(e.querySelectorAll('.semi-form-field')).filter(n=>n.getBoundingClientRect().height>0),button=Array.from(e.querySelectorAll('button')).find(n=>n.textContent==='保存');return {nested:fields[1].getBoundingClientRect().top-fields[0].getBoundingClientRect().bottom,group:fields[2].getBoundingClientRect().top-fields[1].getBoundingClientRect().bottom,actions:button.getBoundingClientRect().top-fields[2].getBoundingClientRect().bottom};});
 assert.deepEqual(await geometry(),{nested:20,group:20,actions:20});
 await section.getByRole('button',{name:'保存'}).click();await section.getByText('请填写组外字段',{exact:true}).waitFor();assert.deepEqual(await geometry(),{nested:20,group:20,actions:20});
 await section.getByRole('textbox',{name:'组外字段'}).fill('完成');await section.getByRole('button',{name:'保存'}).click();await p.getByText('事务完成',{exact:true}).waitFor();assert.deepEqual(await geometry(),{nested:20,group:20,actions:20});}));

test('字段分组不能脱离 FloatingForm 静默回退原生间距',()=>scenario(async p=>{await p.getByRole('button',{name:'错误组合'}).click();await p.getByRole('alert').filter({hasText:'FloatingForm.Fields must be inside FloatingForm'}).waitFor();}));

test('公共 token 同时驱动浮层行内布局与 Semi 生成主题',()=>scenario(async p=>{
 await p.evaluate(()=>{for(const [key,value] of Object.entries({'--eva-space-1':'6px','--eva-space-2':'10px','--eva-space-3':'14px','--eva-space-4':'18px','--eva-space-5':'24px','--eva-fw-regular':'450','--eva-fw-medium':'550'}))document.body.style.setProperty(key,value);});
 await p.getByRole('button',{name:'多字段布局'}).click();
 const dialog=p.getByRole('dialog',{name:'多字段表单'});
 const actual=await dialog.evaluate(e=>{const label=e.querySelector('.semi-form-field-label'),field=e.querySelector('.semi-form-field'),input=field.querySelector('.semi-input-wrapper'),form=e.querySelector('form'),title=document.getElementById(e.getAttribute('aria-labelledby')),button=[...e.querySelectorAll('button')].find(n=>n.textContent==='保存');return {labelWeight:getComputedStyle(label).fontWeight,labelGap:input.getBoundingClientRect().top-label.getBoundingClientRect().bottom,fieldGap:getComputedStyle(form).gap,titleGap:label.getBoundingClientRect().top-title.getBoundingClientRect().bottom,titleWeight:getComputedStyle(title).fontWeight,buttonWeight:getComputedStyle(button).fontWeight,actionGap:getComputedStyle(button.parentElement).marginTop,buttonGap:getComputedStyle(button.parentElement).gap};});
 assert.deepEqual(actual,{labelWeight:'450',labelGap:10,fieldGap:'24px',titleGap:6,titleWeight:'550',buttonWeight:'450',actionGap:'24px',buttonGap:'10px'});
}));
