import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {build} from 'esbuild';
import {chromium} from 'playwright';
import {createServer} from '../../tools/serve.mjs';

test('Popconfirm 共享主题：Portal、亮暗、文字、间距、取消与危险动作',async()=>{
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'eva-theme-test-'));
 for(const name of ['prototype','vendor'])fs.symlinkSync(path.resolve('dist',name),path.join(tmp,name),'dir');
 const css=fs.readFileSync('dist/index.html','utf8').match(/<link[^>]+stylesheet[^>]*>/g).join('\n');
 const code=`import React from 'react';import{createRoot}from'react-dom/client';import{Popconfirm}from'./prototype/063-popconfirm.jsx';import{Popover}from'./prototype/063-popover.jsx';
 const longText="很长的说明内容需要自然换行并保持在浮层内部".repeat(12);function App(){const[done,set]=React.useState(false);return <><Popover content="键盘可读提示"><button>悬停信息</button></Popover><Popover trigger="click" title="长文案" content={longText}><button>长说明</button></Popover><Popconfirm title="单句确认" showArrow={false}><button>单句</button></Popconfirm><Popover trigger="click" position="bottomLeft" content={<div style={{padding:20}}>项目说明内容</div>}><button>项目说明</button></Popover><Popconfirm title="确认操作" content="这是一段用于验证主题的说明" icon={null} showArrow={false} onConfirm={()=>set(true)}><button>普通操作</button></Popconfirm><Popconfirm okButtonProps={{size:"small"}} cancelButtonProps={{size:"small"}} title="确认移除" content="移除后可重新添加" icon={null} showArrow={false} okType="danger" okText="移除"><button>危险操作</button></Popconfirm>{done&&<p>已完成</p>}</>};createRoot(document.getElementById('app')).render(<App/>);`;
 const result=await build({stdin:{contents:code,loader:'jsx',resolveDir:process.cwd()},bundle:true,write:false,loader:{'.css':'empty'}});
 fs.writeFileSync(path.join(tmp,'app.js'),result.outputFiles[0].text);
 fs.writeFileSync(path.join(tmp,'index.html'),`${css}<div id="app" style="padding:100px"></div><script src="app.js"></script>`);
 const server=createServer(tmp);await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({channel:'msedge'}),page=await browser.newPage({viewport:{width:1200,height:800}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 const palettes=[],shadows=[];
 for(const theme of ['light','dark']){
  await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);
  await page.getByRole('button',{name:'普通操作',exact:true}).click();
  const card=page.locator('.semi-popconfirm');await card.waitFor();
  palettes.push(await card.evaluate(el=>({surface:getComputedStyle(el.closest('.semi-popover-wrapper')).backgroundColor,text:getComputedStyle(el.querySelector('.semi-popconfirm-body')).color})));
  shadows.push(await card.evaluate(el=>getComputedStyle(el.closest('.semi-popover-wrapper')).boxShadow));
  const values=await card.evaluate(el=>{
   const style=s=>getComputedStyle(el.querySelector(s));
   return {title:style('.semi-popconfirm-header-title').fontSize,weight:style('.semi-popconfirm-header-title').fontWeight,body:getComputedStyle(el).fontSize,padding:style('.semi-popconfirm-inner').paddingTop,radius:getComputedStyle(el.closest('.semi-popover-wrapper')).borderRadius,portal:!document.getElementById('app').contains(el)};
  });
  assert.deepEqual(values,{title:'14px',weight:'500',body:'14px',padding:'16px',radius:'16px',portal:true});
  await page.evaluate(()=>document.documentElement.style.setProperty('--eva-space-4','28px'));
  assert.equal(await card.locator('.semi-popconfirm-inner').evaluate(el=>getComputedStyle(el).paddingTop),'28px','修改公共间距 token 后浮层自动跟随');
  await page.evaluate(()=>document.documentElement.style.removeProperty('--eva-space-4'));
  await card.getByRole('button',{name:'取消',exact:true}).click();await card.waitFor({state:'hidden'});
 }
 assert.notEqual(palettes[0].surface,palettes[1].surface,'暗色浮层表面跟随公共主题');
 assert.notEqual(palettes[0].text,palettes[1].text,'暗色正文跟随公共主题');
 assert.notEqual(shadows[0],shadows[1],'Popconfirm 投影跟随亮暗公共 token');
 await page.getByRole('button',{name:'普通操作',exact:true}).click();await page.getByRole('button',{name:'确定',exact:true}).click();await page.getByText('已完成',{exact:true}).waitFor();await page.locator('.semi-popconfirm').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'危险操作',exact:true}).click();
 assert.match(await page.getByRole('button',{name:'移除',exact:true}).getAttribute('class'),/danger/);
 assert.equal(await page.getByRole('button',{name:'移除',exact:true}).evaluate(el=>getComputedStyle(el).fontSize),'12px','紧凑按钮不得被普通按钮字号覆盖');
 await page.locator('.semi-popconfirm').getByRole('button',{name:'取消',exact:true}).click();
 await page.getByRole('button',{name:'项目说明',exact:true}).click();
 const info=page.getByText('项目说明内容',{exact:true});await info.waitFor();
 const popoverShadow=await info.evaluate(el=>getComputedStyle(el.closest('.semi-popover-wrapper')).boxShadow);
 assert.equal(await info.evaluate(el=>getComputedStyle(el.closest('.semi-popover-wrapper')).borderRadius),'16px');
 assert.equal(await info.evaluate(el=>getComputedStyle(el).fontSize),'14px');
 await page.keyboard.press('Escape');await info.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'项目说明',exact:true}).click();await info.waitFor();
 await page.locator('#app').click({position:{x:10,y:10}});await info.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'单句',exact:true}).click();
 const single=page.locator('.semi-popconfirm');await single.waitFor();
 assert.equal(await single.evaluate(el=>getComputedStyle(el.closest('.semi-popover-wrapper')).boxShadow),popoverShadow,'Popover 与 Popconfirm 共用卡片浮层投影');
 assert.equal(await page.getByRole('dialog',{name:'单句确认',exact:true}).count(),1);
 assert.equal(await single.getByRole('button',{name:'取消',exact:true}).evaluate(el=>el===document.activeElement),true,'默认聚焦取消');
 await page.keyboard.press('Shift+Tab');
 assert.equal(await single.getByRole('button',{name:'确定',exact:true}).evaluate(el=>el===document.activeElement),true,'反向 Tab 留在按钮区');
 await page.keyboard.press('Tab');
 assert.equal(await single.getByRole('button',{name:'取消',exact:true}).evaluate(el=>el===document.activeElement),true,'正向 Tab 返回取消');
 assert.equal(await single.locator('.semi-popconfirm-header-title').evaluate(el=>getComputedStyle(el).fontWeight),'400');
 assert.equal(await single.locator('.semi-popconfirm-header-icon .semi-icon').evaluate(el=>getComputedStyle(el).fontSize),'18px');
 assert.equal(await single.getByRole('button',{name:'确定',exact:true}).evaluate(el=>getComputedStyle(el).height),'24px');
 const sizes=await single.evaluate(el=>{const a=el.querySelectorAll('button');return {innerShadow:getComputedStyle(el).boxShadow,gap:a[1].offsetLeft-a[0].offsetLeft-a[0].offsetWidth,padding:getComputedStyle(a[0]).paddingLeft};});
 assert.deepEqual(sizes,{innerShadow:'none',gap:8,padding:'11px'});
 await page.keyboard.press('Escape');await single.waitFor({state:'hidden'});
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'单句');
 await page.getByRole('button',{name:'单句',exact:true}).press('Enter');await single.waitFor();
 await page.keyboard.press('Tab');
 assert.equal(await single.evaluate(el=>el.contains(document.activeElement)),true,'键盘打开后可进入确认框操作区');
 await page.keyboard.press('Escape');await single.waitFor({state:'hidden'});
 await page.setViewportSize({width:375,height:700});
 await page.getByRole('button',{name:'长说明',exact:true}).click();
 const long=page.getByText('很长的说明内容需要自然换行并保持在浮层内部'.repeat(12),{exact:true});await long.waitFor();
 assert.equal(await page.getByRole('dialog',{name:'长文案',exact:true}).evaluate(el=>el.contains(document.activeElement)),true);
 const geometry=await long.evaluate(el=>{const p=el.closest('.semi-popover-wrapper');return {max:getComputedStyle(p).maxWidth,width:p.offsetWidth,overflow:p.scrollWidth>p.clientWidth};});
 assert.equal(geometry.max,'343px');assert.ok(geometry.width<=343);assert.equal(geometry.overflow,false);
 await page.keyboard.press('Escape');await long.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'长说明',exact:true}).click();await long.waitFor();
 assert.equal(await page.getByRole('dialog',{name:'长文案',exact:true}).evaluate(el=>el.contains(document.activeElement)),true,'重开后焦点不引用旧节点');
 await page.keyboard.press('Escape');await long.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'悬停信息',exact:true}).focus();
 await page.getByText('键盘可读提示',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'悬停信息','纯信息浮层不抢焦点');
 await page.keyboard.press('Escape');await page.getByText('键盘可读提示',{exact:true}).waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(r=>server.close(r));fs.rmSync(tmp,{recursive:true,force:true});}
});
