import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {loadIdentityEnvironment} from './helpers/identity-environment.mjs';
function setup(){const window={};loadIdentityEnvironment(window);vm.runInNewContext(fs.readFileSync('prototype/009-2-membership.js','utf8'),{window});const s=window.EvaMembership.create({people:[{id:'a',name:'甲',active:true},{id:'b',name:'乙',active:true}]});s.createProject('p','项目','a',[]);s.addMember('p','a','b');s.createThread('t','all:p',{status:1},'a');return s;}
test('隐藏和置顶按账号隔离，保留归档、消息与访问权，并可恢复',()=>{const s=setup();s.setChatPreferences('t','a',{hidden:true,top:true});assert.equal(s.chatPreferences('t','a').hidden,true);assert.equal(s.chatPreferences('t','b').hidden,undefined);assert.equal(s.canRead('t','a'),true);s.updateThread('t',{status:2},'a');s.setChatPreferences('t','a',{hidden:false});assert.equal(s.snapshot().threadDetails.t.status,2);assert.equal(s.chatPreferences('t','a').top,true);const restored=windowlessRestore(s);assert.equal(restored.chatPreferences('t','a').hidden,false);});
function windowlessRestore(s){const window={};loadIdentityEnvironment(window);vm.runInNewContext(fs.readFileSync('prototype/009-2-membership.js','utf8'),{window});return window.EvaMembership.create(s.snapshot());}
test('子区个人设置不能绕过父群权限',()=>{const s=setup();s.createGroup('g','小群','p','a',[]);s.createThread('private','g',{status:1},'a');assert.throws(()=>s.setChatPreferences('private','b',{hidden:true}));});
test('明确@本人恢复隐藏，普通消息、@所有人和@分身不恢复；保留其他偏好',()=>{const s=setup();s.setChatPreferences('t','a',{hidden:true,restoreOnMention:true,top:true,mute:true});s.updateThread('t',{status:2},'a');s.sendMessage('t','b','普通更新');assert.equal(s.chatPreferences('t','a').hidden,true);s.sendMessage('t','b','@所有人 请查看');assert.equal(s.chatPreferences('t','a').hidden,true);s.sendMessage('t','b','@甲分身 请查看');assert.equal(s.chatPreferences('t','a').hidden,true);s.sendMessage('t','b','@甲 请确认');assert.equal(s.chatPreferences('t','a').hidden,false);assert.equal(s.chatPreferences('t','a').restoreOnMention,true);assert.equal(s.chatPreferences('t','a').top,true);assert.equal(s.chatPreferences('t','a').mute,true);assert.equal(s.snapshot().threadDetails.t.status,2);});
test('自动恢复默认关闭，历史消息读取不恢复',()=>{const s=setup();s.setChatPreferences('t','a',{hidden:true});s.sendMessage('t','b','@甲 请确认');assert.equal(s.chatPreferences('t','a').hidden,true);s.setChatPreferences('t','a',{restoreOnMention:true});s.messagesFor('t','a');assert.equal(s.chatPreferences('t','a').hidden,true);});

test('清除未读按账号和会话隔离，保留消息并继续累计新消息',()=>{const s=setup();s.sendMessage('t','b','初始消息');s.clearConversationUnread('t','a');assert.equal(s.conversationUnread('t','a',3),0);assert.equal(s.conversationUnread('t','b',3),3);assert.equal(s.conversationUnread('all:p','a',4),4);s.sendMessage('t','a','自己的消息');assert.equal(s.conversationUnread('t','a',3),0);s.sendMessage('t','b','新消息');assert.equal(s.conversationUnread('t','a',3),1);assert.equal(windowlessRestore(s).conversationUnread('t','a',3),1);assert.equal(s.messagesFor('t','a').length,3);});
test('子区免打扰默认继承父群，显式设置优先',()=>{const s=setup();s.setChatPreferences('all:p','a',{mute:true});assert.equal(s.conversationMuted('t','a'),true);s.setChatPreferences('t','a',{mute:false});assert.equal(s.conversationMuted('t','a'),false);assert.equal(s.conversationMuted('all:p','a'),true);assert.equal(s.conversationMuted('t','b'),false);});

test('不显示仅保存当前账号的最近偏好，保留消息及置顶，新消息恢复',()=>{const s=setup();s.sendMessage('t','b','保留记录');s.setChatPreferences('t','a',{top:true});s.hideRecentConversation('t','a');assert.equal(s.recentConversationHidden('t','a'),true);assert.equal(s.recentConversationHidden('t','b'),false);assert.equal(s.chatPreferences('t','a').hidden,undefined);assert.equal(s.chatPreferences('t','a').top,true);assert.equal(s.conversationUnread('t','a',2),0);assert.equal(s.messagesFor('t','a').length,1);assert.equal(windowlessRestore(s).recentConversationHidden('t','a'),true);s.sendMessage('t','b','新消息');assert.equal(s.recentConversationHidden('t','a'),false);assert.equal(s.conversationUnread('t','a',2),1);});
